### ISSUE TITLE
sfdc-copy-opportunity-line-item-custom-fields-to-quote-line-items

### ISSUE THREAD

**Issue by ramajj** [DouglasCAyers/sfdc-copy-opportunity-line-item-custom-fields-to-quote-line-items#1]
Does anyone know if is it possible to install this app [sfdc-copy-opportunity-line-item-custom-fields-to-quote-line-items](url) in salesforce professional? I have been trying without success.. by the moment I try to deploy I get this message: 

"Oops, something went wrong...
Authentication Failed: OAuth login invalid or expired access token

Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

Logout"

Let me know if you have any ideas to get trough this.. 

Thank you in advance!

**Comment by douglascayers** [comment]
Hello, thanks for your interest in my app. Unfortunately this is not supported in Professional Edition because it uses Apex. To use this package then you will either need to:

1. Contact support to see what is needed to enable Apex in your Edition. This likely requires an upcharge. 

2. Upgrade to Enterprise Edition to unlock all features of the platform
